#
# Copyright (c) 2024-2026 by the CRESCENT cyberinfrastructure team (https://cascadiaquakes.org/)
# See LICENSE for copying and redistribution conditions.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 3 or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# Contact info: abioyeajala@gmail.com (Rasheed Ajala)
#-------------------------------------------------------------------------------
#
# Default gq settings. DO NOT EDIT THIS FILE!
#
# There are two configuration files:
#   1) "ConfigDefault.cmake" - is version controlled and used to add new default
#      variables and set defaults for everyone.
#   2) "ConfigUser.cmake" - is ignored by Git and used to override defaults
#      on a per-user basis.
#
# NOTE: If you want to change CMake behaviour just for yourself then copy
#      "ConfigUserTemplate.cmake" to "ConfigUser.cmake" and then edit
#      "ConfigUser.cmake" (not "ConfigDefault.cmake" or "ConfigUserTemplate.cmake").
#

set (GQ_PACKAGE_NAME "gq")
set (GQ_PACKAGE_DESCRIPTION_SUMMARY
	"Model and data merging and retrofitting")

set (GQ_PACKAGE_VERSION_MAJOR 1)
set (GQ_PACKAGE_VERSION_MINOR 0)
set (GQ_PACKAGE_VERSION_PATCH 1)
set (GQ_PACKAGE_VERSION
	"${GQ_PACKAGE_VERSION_MAJOR}.${GQ_PACKAGE_VERSION_MINOR}.${GQ_PACKAGE_VERSION_PATCH}")

# Optional build components are disabled for a normal user build.
if (NOT DEFINED GQ_BUILD_TESTS)
	set (GQ_BUILD_TESTS OFF)
endif ()
if (NOT DEFINED GQ_BUILD_EXAMPLES)
	set (GQ_BUILD_EXAMPLES OFF)
endif ()
if (NOT DEFINED GQ_BUILD_DOCS)
	set (GQ_BUILD_DOCS OFF)
endif ()

# Single-configuration generators use Release unless the user selects another
# build type. Multi-configuration generators choose at build time.
if (NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
	set (CMAKE_BUILD_TYPE Release CACHE STRING
		"Build type: Debug, Release, RelWithDebInfo, or MinSizeRel" FORCE)
endif ()


# vim: textwidth=78 noexpandtab tabstop=2 softtabstop=2 shiftwidth=2
